In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)  

In [2]:
df = pd.read_csv('../sample_csv_data/ohport_downsampling_iot_flow.csv')
df = df.drop(columns=['Unnamed: 0'])

In [3]:
df.head()

timeStampFirst  timeStampLast  duration linkProtocol networkProtocol  \
0   1475671755714  1475671756741      1027     Ethernet            IPv4   
1   1475020226003  1475020226003         0     Ethernet            IPv4   
2   1476208177398  1476208177427        29     Ethernet            IPv4   
3   1474599250064  1474599250086        22     Ethernet            IPv4   
4   1476049394301  1476049394604       303     Ethernet            IPv4   

  transportProtocol applicationProtocol             srcMac             dstMac  \
0               TCP                 NaN  ec:1a:59:83:28:11  ec:1a:59:79:f4:89   
1               UDP                 DNS  00:16:6c:ab:6b:88  14:cc:20:51:33:ea   
2               TCP                 NaN  ec:1a:59:79:f4:89  ec:1a:59:83:28:11   
3               TCP                 NaN  00:16:6c:ab:6b:88  ec:1a:59:83:28:11   
4               TCP                 NaN  44:65:0d:56:cc:d3  14:cc:20:51:33:ea   

           srcIP          dstIP  srcPort  dstPort  packetCount  \
0  192.168.1.193  192.168.1.223  49153.0   3538.0            6   
1  192.168.1.249    192.168.1.1  50591.0     53.0            2   
2  192.168.1.223  192.168.1.193  49152.0   4018.0            7   
3  192.168.1.249  192.168.1.193  49152.0   4415.0            5   
4  192.168.1.240  93.184.216.34  53974.0     80.0            4   

   totalPayloadByte  appplicationPayloadByte   iot                     device  \
0               597                        0  True  Belkin wemo motion sensor   
1               148                        0  True           Samsung SmartCam   
2              4087                        0  True         Belkin Wemo switch   
3              1508                        0  True           Samsung SmartCam   
4               272                        0  True                Amazon Echo   

   dns  dhcp-server  http  ntp  https  smtp-ssl  imap-ssl  ssdp  icslap  \
0  0.0          0.0   0.0  0.0    0.0       0.0       0.0   0.0     0.0   
1  1.0          0.0   0.0  0.0    0.0       0.0       0.0   0.0     0.0   
2  0.0          0.0   0.0  0.0    0.0       0.0       0.0   0.0     0.0   
3  0.0          0.0   0.0  0.0    0.0       0.0       0.0   0.0     0.0   
4  0.0          0.0   1.0  0.0    0.0       0.0       0.0   0.0     0.0   

   stm-pproc  stun  ws-discovery  upnp-evnt  xmpp  android  dstPort25050  \
0        0.0   0.0           0.0        0.0   0.0      0.0           0.0   
1        0.0   0.0           0.0        0.0   0.0      0.0           0.0   
2        0.0   0.0           0.0        0.0   0.0      0.0           0.0   
3        0.0   0.0           0.0        0.0   0.0      0.0           0.0   
4        0.0   0.0           0.0        0.0   0.0      0.0           0.0   

   dstPort49152  dstPort49153  dstPort49154  wellKnownDstPort  \
0           0.0           0.0           0.0               0.0   
1           0.0           0.0           0.0               0.0   
2           0.0           0.0           0.0               0.0   
3           0.0           0.0           0.0               0.0   
4           0.0           0.0           0.0               0.0   

   ephemeralDstPort  registedDstPort  srcPort49152  srcPort49153  
0               0.0              1.0           0.0           1.0  
1               0.0              1.0           0.0           0.0  
2               0.0              1.0           1.0           0.0  
3               0.0              1.0           1.0           0.0  
4               0.0              1.0           0.0           0.0

In [4]:
one_hot = pd.get_dummies(df['networkProtocol'])
df = df.join(one_hot)
one_hot = pd.get_dummies(df['transportProtocol'])
df = df.join(one_hot)

In [5]:
device_list = df.device.unique()
device_dict = dict(zip(device_list, range(len(device_list))))
tf_df = df.replace({'device': device_dict})

In [6]:
df.head()

timeStampFirst  timeStampLast  duration linkProtocol networkProtocol  \
0   1475671755714  1475671756741      1027     Ethernet            IPv4   
1   1475020226003  1475020226003         0     Ethernet            IPv4   
2   1476208177398  1476208177427        29     Ethernet            IPv4   
3   1474599250064  1474599250086        22     Ethernet            IPv4   
4   1476049394301  1476049394604       303     Ethernet            IPv4   

  transportProtocol applicationProtocol             srcMac             dstMac  \
0               TCP                 NaN  ec:1a:59:83:28:11  ec:1a:59:79:f4:89   
1               UDP                 DNS  00:16:6c:ab:6b:88  14:cc:20:51:33:ea   
2               TCP                 NaN  ec:1a:59:79:f4:89  ec:1a:59:83:28:11   
3               TCP                 NaN  00:16:6c:ab:6b:88  ec:1a:59:83:28:11   
4               TCP                 NaN  44:65:0d:56:cc:d3  14:cc:20:51:33:ea   

           srcIP          dstIP  srcPort  dstPort  packetCount  \
0  192.168.1.193  192.168.1.223  49153.0   3538.0            6   
1  192.168.1.249    192.168.1.1  50591.0     53.0            2   
2  192.168.1.223  192.168.1.193  49152.0   4018.0            7   
3  192.168.1.249  192.168.1.193  49152.0   4415.0            5   
4  192.168.1.240  93.184.216.34  53974.0     80.0            4   

   totalPayloadByte  appplicationPayloadByte   iot                     device  \
0               597                        0  True  Belkin wemo motion sensor   
1               148                        0  True           Samsung SmartCam   
2              4087                        0  True         Belkin Wemo switch   
3              1508                        0  True           Samsung SmartCam   
4               272                        0  True                Amazon Echo   

   dns  dhcp-server  http  ntp  https  smtp-ssl  imap-ssl  ssdp  icslap  \
0  0.0          0.0   0.0  0.0    0.0       0.0       0.0   0.0     0.0   
1  1.0          0.0   0.0  0.0    0.0       0.0       0.0   0.0     0.0   
2  0.0          0.0   0.0  0.0    0.0       0.0       0.0   0.0     0.0   
3  0.0          0.0   0.0  0.0    0.0       0.0       0.0   0.0     0.0   
4  0.0          0.0   1.0  0.0    0.0       0.0       0.0   0.0     0.0   

   stm-pproc  stun  ws-discovery  upnp-evnt  xmpp  android  dstPort25050  \
0        0.0   0.0           0.0        0.0   0.0      0.0           0.0   
1        0.0   0.0           0.0        0.0   0.0      0.0           0.0   
2        0.0   0.0           0.0        0.0   0.0      0.0           0.0   
3        0.0   0.0           0.0        0.0   0.0      0.0           0.0   
4        0.0   0.0           0.0        0.0   0.0      0.0           0.0   

   dstPort49152  dstPort49153  dstPort49154  wellKnownDstPort  \
0           0.0           0.0           0.0               0.0   
1           0.0           0.0           0.0               0.0   
2           0.0           0.0           0.0               0.0   
3           0.0           0.0           0.0               0.0   
4           0.0           0.0           0.0               0.0   

   ephemeralDstPort  registedDstPort  srcPort49152  srcPort49153  IPv4  IPv6  \
0               0.0              1.0           0.0           1.0     1     0   
1               0.0              1.0           0.0           0.0     1     0   
2               0.0              1.0           1.0           0.0     1     0   
3               0.0              1.0           1.0           0.0     1     0   
4               0.0              1.0           0.0           0.0     1     0   

   TCP  UDP  
0    1    0  
1    0    1  
2    1    0  
3    1    0  
4    1    0

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [34]:
# def process_features(df, train, test):
#     continuous = ['duration', 'packetCount', 'totalPayloadByte', 'appplicationPayloadByte']
#     cs = MinMaxScaler()
#     trainContinuous = cs.fit_transform(train[continuous])
#     testContinuous = cs.fit_transform(test[continuous])
#     return trainContinuous, testContinuous
# train, test = train_test_split(df, test_size = 0.3, random_state = 42)
# trainX, testX = process_features(df, train, test)
# print(trainX)

[[1.35780784e-02 0.00000000e+00 1.22175975e-06 1.85950413e-02]
 [1.82448691e-04 7.94770698e-06 1.65587439e-05 0.00000000e+00]
 [8.51344929e-09 2.16755645e-06 5.61489589e-06 0.00000000e+00]
 ...
 [6.08103521e-10 0.00000000e+00 7.53851763e-07 0.00000000e+00]
 [1.28917946e-07 2.89007526e-06 7.07060964e-06 0.00000000e+00]
 [3.43039710e-04 8.67022579e-06 9.74808315e-06 6.88705234e-04]]


/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)
/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [8]:
oh_ports = [
    'https',
    'http',
    'dns',
    'dstPort49152',
    'dstPort49153',
    'ntp',
    'ws-discovery',
    'upnp-evnt',
    'xmpp',
    'ssdp',
    'smtp-ssl',
    'dstPort25050',
    'stun',
    'dstPort49154',
    'android',
    'imap-ssl',
    'stm-pproc',
    'dhcp-server',
    'icslap',
    'srcPort49152',
    'srcPort49153',
    'wellKnownDstPort',
    'ephemeralDstPort', 
    'registedDstPort'
]

categoricals = ['IPv4', 'IPv6', 'TCP', 'UDP'] + oh_ports
continuous = ['duration', 'packetCount', 'totalPayloadByte', 'appplicationPayloadByte']
X_con = df[continuous].values[:,:]
scaler = StandardScaler()
print(X_con)
X_scaled = scaler.fit_transform(X_con)
# print(X_scaled)

# m = MinMaxScaler()
# X_scaled_mm = m.fit_transform(X_con)
# print(X_scaled_mm)
X_cat = df[categoricals].values[:,:]
X = np.hstack([X_scaled, X_cat])
# feature_cols = ['duration','packetCount', 'totalPayloadByte', 'appplicationPayloadByte', 
#                 'IPv4', 'IPv6', 'TCP', 'UDP'] + oh_ports
# X = df[feature_cols].values[:,:]
Y = df[['iot']].values[:]
Y = Y.astype('int')
# scaler = StandardScaler()
# print(X)
# scaler.fit(X)
# X = scaler.transform(X)
# print(X)
# cs = MinMaxScaler()
# cc = cs.fit_transform(X['duration', 'packetCount', 'totalPayloadByte', 'appplicationPayloadByte'])
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100)
print(X_train)

[[1027    6  597    0]
 [   0    2  148    0]
 [  29    7 4087    0]
 ...
 [  69    6  957    0]
 [  10    6  957    0]
 [  19    6  957    0]]
[[-0.17840216 -0.00675196 -0.01410938 ...  0.          0.
   1.        ]
 [-0.17627669 -0.00601081 -0.01070445 ...  0.          0.
   1.        ]
 [-0.17840795 -0.00823425 -0.01629694 ...  0.          1.
   0.        ]
 ...
 [-0.1656972  -0.0089754  -0.01701068 ...  0.          0.
   1.        ]
 [-0.17839068 -0.00872835 -0.01708174 ...  0.          0.
   1.        ]
 [-0.178408   -0.00823425 -0.0132566  ...  0.          0.
   1.        ]]


/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [14]:
models = [
    {
        'model': DecisionTreeClassifier(random_state = 100),
        'name': 'Decision Tree',
        'active': True
    },
    {
        'model': KNeighborsClassifier(n_neighbors=3),
        'name': 'KNN',
        'active': True
    },
    {
        'model': GaussianNB(),
        'name': 'GaussianNB',
        'active': True
    },
    {
        'model':  RandomForestClassifier(n_estimators=100),
        'name': 'Random Forest',
        'active': True
    },
    
    {
        'model': AdaBoostClassifier(n_estimators=100),
        'name': 'Ada Boosting Decision Tree',
        'active': False
    },
    {
        'model': GradientBoostingClassifier(n_estimators=100),
        'name': 'Gradient Boosting Decision Tree',
        'active': False
    },
    {
        'model': LogisticRegression(random_state=0, solver='liblinear', multi_class='ovr'),
        'name': 'Logistic Regression',
        'active': True
    }
]

In [15]:
for m in models:
    if m['active'] == True:
        m['model'].fit(X_train, y_train)
        y_pred = m['model'].predict(X_test)
        print(m['name'], "accurency is", accuracy_score(y_test,y_pred), "\nf1 score is", f1_score(y_test, y_pred), "\n")

Decision Tree accurency is 0.9844852285320431 
f1 score is 0.9844890017834946 



/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


KNN accurency is 0.9808362840230289 
f1 score is 0.9808383557201158 

GaussianNB accurency is 0.80893045382058 
f1 score is 0.7736833680166478 



/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


Random Forest accurency is 0.9880260561667162 
f1 score is 0.9879949052871196 



/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Logistic Regression accurency is 0.8628807741168203 
f1 score is 0.8526875163341755 



In [ ]:
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(models[0]['model'], out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue()) 

In [ ]:
graph.write_pdf("iris.pdf")

In [186]:
from sklearn.model_selection import cross_val_score

In [9]:
model = RandomForestClassifier(n_estimators=100)

In [196]:
# scores = cross_val_score(model, X, Y, cv=10)

In [195]:
# print("Accuracy: %0.5f (+/- %0.5f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.98489 (+/- 0.00758)


In [10]:
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [11]:
y_pred = clf.predict(X_test)

In [24]:
# print(accuracy_score(y_test,y_pred))
# print(f1_score(y_test, y_pred))
features = continuous + categoricals
i = 0
for f in features:
    print(clf.feature_importances_[i]*100)
    i+=1

18.087803057743542
10.228802263330316
21.870158987376875
7.504518514135182
1.043556726387738
1.2482258409726188
1.2286448376956567
1.2876671634817751
9.093953445745305
2.0652369588387987
1.1851256716729859
0.769734625772962
0.6993408117153345
2.186105872123254
1.2479043433011565
1.967463138686275
0.8048730231067417
0.1260511642258242
1.4349860091267135
0.7340677798494308
0.27754545703794725
0.037328124581950936
0.38366214739695753
0.17125589352330645
0.2115483191725938
0.0979714595699258
0.1792672680756456
4.430920908479759
3.8416274326774595
0.0
2.8701767232623747
2.6844760309335753


In [105]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [111]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[18318   195]
 [  260 18224]]


In [114]:
from sklearn.externals import joblib
joblib.dump(clf, 'saved_model.pkl')

['saved_model.pkl']